### ISSUE TITLE
'less' margin and padding classes cause logical conflicts 

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#501]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**

currently the `less` `margin` & `padding` classes make use of `:not` css selector to make sure that `less left padding` has only the left padding as 0 and not all the paddings. 
However `left`, `right`, `top` and `bottom` are global semantic UI classes and more than one of them maybe present in a single element at a time. 
For instance 
```
<div class='ui right aligned column left padding less'>
<!-- This will make both left AND right padding as 0 -->
```
**Expected behavior:**

Only the left padding should have been 0
*This is just an example* 
**Steps to reproduce:**

**Related code:**

```
.less {
  &.margin:not(.bottom):not(.top) {
    margin: 0 !important;
  }

  &.right.margin {
    margin-top: 0 !important;
  }

  &.padding:not(.bottom):not(.top) {
    padding: 0 !important;
  }

  &.right.padding {
    padding-right: 0 !important;
  }

  &.left.padding {
    padding-left: 0 !important;
  }
}
```

**Comment by CosmicCoder96** [comment]
@niranjan94 Please guide

**Comment by niranjan94** [comment]
Instead of the current styles, you can put something like 

```scss

.ui[class*="less margin"] {
	margin: 0 !important;
}

.ui[class*="less padding"] {
	padding: 0 !important;
}

.ui.less {
  &[class*="left margin"] {
    margin-left: 0 !important;
  }

  &[class*="right margin"] {
    margin-right: 0 !important;
  }

  &[class*="right padding"] {
    padding-right: 0 !important;
  }

  &[class*="left padding"] {
    padding-left: 0 !important;
  }
}
```
